export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";

export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";

export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";

export const POST_ACTIVITY = "POST_ACTIVITY";

export const GET_ACTIVITIES = "GET_ACTIVITIES";

export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";

export const NEXT_PAGE = "NEXT_PAGE";

export const PREV_PAGE = "PREV_PAGE";

export const ORDER = "ORDER";

export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";

export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";